version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    network_mode: 'host'

  mysql:
    platform: linux/x86_64
    build:
      context: ./docker
    container_name: node_sql
    volumes:
      - ./docker/db_data:/var/lib/mysql
    ports:
      - "3306:3306"