# Use a imagem oficial do MySQL
FROM mysql:8

# Define variáveis de ambiente para configurar o MySQL
ENV MYSQL_ROOT_PASSWORD=contar123
ENV MYSQL_DATABASE=contardb
ENV MYSQL_USER=contar
ENV MYSQL_PASSWORD=contar